name: dotnet format

on:
  push:
  pull_request:
    branches: [main]
    paths:
      - "**.cs"
      - ".editorconfig"

env:
  DOTNET_VERSION: "7.0.100"

jobs:
  check-format:
    runs-on: linux-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run dotnet format
        run: dotnet format '.\' --folder --check --verbosity diagnostic
