---
name: Lint

on:
  push:
  pull_request:
    branches: [main]
    paths:
      - "**.cs"
      - ".editorcobfing"

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format
      - name: Run dotnet format
         run: dotnet format ''.\'' --folder --check --verbosity diagnostic

      - name: Run linters
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: ${{ github.base_ref }}
          LINTER_RULES_PATH: /src/
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CSHARP: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
